package generator

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/format"
	"go/types"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	contractsPath = "github.com/mirkobrombin/go-foundation/v2/core/contracts"
	appPath       = "github.com/mirkobrombin/go-foundation/v2/app"
	actionsPath   = "github.com/mirkobrombin/go-foundation/v2/app/actions"
	webPath       = "github.com/mirkobrombin/go-foundation/v2/app/web"
	generatedFile = "zz_foundation.gen.go"
	generatedMark = "// Code generated by foundation generate. DO NOT EDIT.\n"
)

// Output is generated source for one package.
type Output struct {
	Path    string
	Content []byte
}

type contract struct {
	implementation string
	target         string
}

type route struct {
	implementation string
	method         string
	path           string
}

type action struct {
	implementation string
	name           string
	key            string
}

type packageModel struct {
	name      string
	path      string
	contracts []contract
	routes    []route
	actions   []action
	imports   *imports
}

// Load renders generated source for matching packages without writing files.
func Load(ctx context.Context, dir string, patterns ...string) ([]Output, error) {
	outputs, _, err := load(ctx, dir, patterns...)
	return outputs, err
}

func load(ctx context.Context, dir string, patterns ...string) ([]Output, []string, error) {
	moduleRoot, err := canonicalModuleRoot(dir)
	if err != nil {
		return nil, nil, err
	}
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}
	cfg := &packages.Config{
		Context: ctx,
		Dir:     dir,
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedImports |
			packages.NeedDeps,
	}
	loaded, err := packages.Load(cfg, patterns...)
	if err != nil {
		return nil, nil, err
	}
	var loadErrors []string
	provisionalErrors := make(map[*packages.Package][]packages.Error)
	for _, pkg := range loaded {
		for _, loadErr := range pkg.Errors {
			if strings.Contains(loadErr.Pos, generatedFile+":") {
				continue
			}
			if _, ok := generatedSymbolError(loadErr); ok {
				provisionalErrors[pkg] = append(provisionalErrors[pkg], loadErr)
				continue
			}
			loadErrors = append(loadErrors, loadErr.Error())
		}
	}
	if len(loadErrors) > 0 {
		return nil, nil, fmt.Errorf(
			"foundation generate: package loading failed:\n%s",
			strings.Join(loadErrors, "\n"),
		)
	}

	var outputs []Output
	directories := make(map[string]struct{})
	for _, pkg := range loaded {
		if len(pkg.CompiledGoFiles) > 0 {
			directory, err := canonicalPackageDirectory(pkg.CompiledGoFiles[0], moduleRoot)
			if err != nil {
				return nil, nil, err
			}
			directories[directory] = struct{}{}
		}
		output, ok, err := renderPackage(pkg)
		if err != nil {
			return nil, nil, err
		}
		for _, loadErr := range provisionalErrors[pkg] {
			name, _ := generatedSymbolError(loadErr)
			signature := []byte("func " + name + "(")
			if !ok || !bytes.Contains(output.Content, signature) {
				return nil, nil, fmt.Errorf(
					"foundation generate: package loading failed:\n%s",
					loadErr.Error(),
				)
			}
		}
		if ok {
			if err := ensureWithinModule(output.Path, moduleRoot); err != nil {
				return nil, nil, err
			}
			outputs = append(outputs, output)
		}
	}
	sort.Slice(outputs, func(i, j int) bool {
		return outputs[i].Path < outputs[j].Path
	})
	packageDirectories := make([]string, 0, len(directories))
	for directory := range directories {
		packageDirectories = append(packageDirectories, directory)
	}
	sort.Strings(packageDirectories)
	return outputs, packageDirectories, nil
}

// Write generates files and returns their paths.
func Write(ctx context.Context, dir string, patterns ...string) ([]string, error) {
	outputs, directories, err := load(ctx, dir, patterns...)
	if err != nil {
		return nil, err
	}
	paths := make([]string, 0, len(outputs))
	expected := make(map[string]struct{}, len(outputs))
	for _, output := range outputs {
		if err := writeFile(output.Path, output.Content); err != nil {
			return nil, err
		}
		expected[output.Path] = struct{}{}
		paths = append(paths, output.Path)
	}
	for _, directory := range directories {
		path := filepath.Join(directory, generatedFile)
		if _, ok := expected[path]; ok {
			continue
		}
		if err := removeGeneratedFile(path); err != nil {
			return nil, err
		}
	}
	return paths, nil
}

// Check reports generated files that are missing or stale.
func Check(ctx context.Context, dir string, patterns ...string) error {
	outputs, directories, err := load(ctx, dir, patterns...)
	if err != nil {
		return err
	}
	var stale []string
	expected := make(map[string]struct{}, len(outputs))
	for _, output := range outputs {
		expected[output.Path] = struct{}{}
		current, err := os.ReadFile(output.Path)
		if err != nil || !bytes.Equal(current, output.Content) {
			stale = append(stale, output.Path)
		}
	}
	for _, directory := range directories {
		path := filepath.Join(directory, generatedFile)
		if _, ok := expected[path]; ok {
			continue
		}
		if _, err := os.Stat(path); err == nil {
			stale = append(stale, path)
		} else if !os.IsNotExist(err) {
			return err
		}
	}
	if len(stale) > 0 {
		sort.Strings(stale)
		return fmt.Errorf("foundation generate: stale files: %s", strings.Join(stale, ", "))
	}
	return nil
}

func generatedSymbolError(err packages.Error) (string, bool) {
	for _, name := range []string{
		"FoundationActions",
		"FoundationHTTPHandlers",
		"RegisterFoundation",
	} {
		if strings.Contains(err.Msg, "undefined: "+name) {
			return name, true
		}
	}
	return "", false
}

func renderPackage(pkg *packages.Package) (Output, bool, error) {
	if len(pkg.CompiledGoFiles) == 0 {
		return Output{}, false, nil
	}

	model := packageModel{
		name:    pkg.Name,
		path:    pkg.PkgPath,
		imports: newImports(pkg.PkgPath),
	}
	for _, file := range pkg.Syntax {
		for _, declaration := range file.Decls {
			generic, ok := declaration.(*ast.GenDecl)
			if !ok || generic.Tok.String() != "type" {
				continue
			}
			for _, rawSpec := range generic.Specs {
				spec, ok := rawSpec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := spec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if err := model.collectType(pkg, spec, structType); err != nil {
					return Output{}, false, err
				}
			}
		}
	}

	if len(model.contracts) == 0 && len(model.routes) == 0 && len(model.actions) == 0 {
		return Output{}, false, nil
	}
	content, err := model.render()
	if err != nil {
		return Output{}, false, err
	}
	return Output{
		Path:    filepath.Join(filepath.Dir(pkg.CompiledGoFiles[0]), generatedFile),
		Content: content,
	}, true, nil
}

func (m *packageModel) collectType(pkg *packages.Package, spec *ast.TypeSpec, structType *ast.StructType) error {
	object := pkg.TypesInfo.Defs[spec.Name]
	if object == nil {
		return nil
	}

	var method, path, actionName, key string
	for _, field := range structType.Fields.List {
		if args, ok := genericSelector(field.Type, pkg, contractsPath, "Implements"); ok {
			target := pkg.TypesInfo.TypeOf(args[0])
			iface, isInterface := target.Underlying().(*types.Interface)
			implementation := object.Type()
			if !isInterface || !types.Implements(types.NewPointer(implementation), iface) {
				return fmt.Errorf(
					"foundation generate: %s.%s does not implement %s",
					pkg.PkgPath,
					spec.Name.Name,
					types.TypeString(target, m.imports.qualifier),
				)
			}
			m.contracts = append(m.contracts, contract{
				implementation: spec.Name.Name,
				target:         types.TypeString(target, m.imports.qualifier),
			})
		}

		if field.Tag == nil {
			continue
		}
		raw, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			continue
		}
		tag := reflect.StructTag(raw)
		if value := tag.Get("method"); value != "" {
			method = value
		}
		if value := tag.Get("path"); value != "" {
			if tag.Get("method") != "" {
				path = value
			}
		}
		if value := tag.Get("action"); value != "" {
			actionName = value
		}
		if value := tag.Get("keys"); value != "" {
			key = value
		}
	}

	if method != "" && path != "" {
		if err := validateRouteDefinition(method, path); err != nil {
			return fmt.Errorf(
				"foundation generate: %s.%s: %w",
				pkg.PkgPath,
				spec.Name.Name,
				err,
			)
		}
		for _, existing := range m.routes {
			if routeBranchConflict(path, existing.path) {
				return fmt.Errorf(
					"foundation generate: %s.%s: route %q conflicts with parameter route %q",
					pkg.PkgPath,
					spec.Name.Name,
					path,
					existing.path,
				)
			}
			if method == existing.method && routeShape(path) == routeShape(existing.path) {
				return fmt.Errorf(
					"foundation generate: %s.%s: route %s %s is already declared",
					pkg.PkgPath,
					spec.Name.Name,
					method,
					path,
				)
			}
		}
		if !foundationHandler(object.Type()) {
			return fmt.Errorf(
				"foundation generate: %s.%s must implement Handle(context.Context) (any, error)",
				pkg.PkgPath,
				spec.Name.Name,
			)
		}
		m.routes = append(m.routes, route{
			implementation: spec.Name.Name,
			method:         method,
			path:           path,
		})
	}
	if actionName != "" {
		if !foundationHandler(object.Type()) {
			return fmt.Errorf(
				"foundation generate: %s.%s must implement Handle(context.Context) (any, error)",
				pkg.PkgPath,
				spec.Name.Name,
			)
		}
		m.actions = append(m.actions, action{
			implementation: spec.Name.Name,
			name:           actionName,
			key:            key,
		})
	}
	return nil
}

func validateRouteDefinition(method, path string) error {
	switch method {
	case http.MethodGet, http.MethodHead, http.MethodPost, http.MethodPut,
		http.MethodPatch, http.MethodDelete, http.MethodConnect,
		http.MethodOptions, http.MethodTrace:
	default:
		return fmt.Errorf("unsupported HTTP method %q", method)
	}
	if !strings.HasPrefix(path, "/") {
		return fmt.Errorf("route path must start with /")
	}
	segments := strings.Split(strings.Trim(path, "/"), "/")
	seen := make(map[string]struct{})
	for index, segment := range segments {
		if !strings.HasPrefix(segment, "{") {
			if strings.ContainsAny(segment, "{}") {
				return fmt.Errorf("malformed route segment %q", segment)
			}
			continue
		}
		if !strings.HasSuffix(segment, "}") {
			return fmt.Errorf("unclosed route parameter %q", segment)
		}
		inner := strings.TrimSuffix(strings.TrimPrefix(segment, "{"), "}")
		if strings.HasPrefix(inner, "*") {
			if index != len(segments)-1 {
				return fmt.Errorf("catch-all parameter must be last")
			}
			inner = strings.TrimPrefix(inner, "*")
			if strings.Contains(inner, ":") {
				return fmt.Errorf("catch-all parameters cannot have constraints")
			}
		}
		if separator := strings.IndexByte(inner, ':'); separator >= 0 {
			if err := validateRouteConstraint(inner[separator+1:]); err != nil {
				return err
			}
			inner = inner[:separator]
		}
		if inner == "" {
			return fmt.Errorf("route parameter name cannot be empty")
		}
		if !validRouteParameterName(inner) {
			return fmt.Errorf("invalid route parameter name %q", inner)
		}
		if _, exists := seen[inner]; exists {
			return fmt.Errorf("duplicate route parameter %q", inner)
		}
		seen[inner] = struct{}{}
	}
	return nil
}

func validateRouteConstraint(value string) error {
	if value == "int" || value == "alpha" {
		return nil
	}
	if strings.HasPrefix(value, "regex(") && strings.HasSuffix(value, ")") {
		if _, err := regexp.Compile(value[6 : len(value)-1]); err != nil {
			return fmt.Errorf("invalid regex constraint: %w", err)
		}
		return nil
	}
	for _, item := range strings.Split(value, ",") {
		if item != "int" && item != "alpha" {
			return fmt.Errorf("unknown route constraint %q", item)
		}
	}
	return nil
}

func routeShape(path string) string {
	segments := strings.Split(strings.Trim(path, "/"), "/")
	for index, segment := range segments {
		if strings.HasPrefix(segment, "{") && strings.HasSuffix(segment, "}") {
			if strings.HasPrefix(segment, "{*") {
				segments[index] = "{*}"
			} else {
				segments[index] = "{}"
			}
		}
	}
	return "/" + strings.Join(segments, "/")
}

func routeBranchConflict(left, right string) bool {
	leftSegments := strings.Split(strings.Trim(left, "/"), "/")
	rightSegments := strings.Split(strings.Trim(right, "/"), "/")
	limit := min(len(leftSegments), len(rightSegments))
	for index := 0; index < limit; index++ {
		leftSegment := leftSegments[index]
		rightSegment := rightSegments[index]
		leftParameter := strings.HasPrefix(leftSegment, "{") && strings.HasSuffix(leftSegment, "}")
		rightParameter := strings.HasPrefix(rightSegment, "{") && strings.HasSuffix(rightSegment, "}")
		if !leftParameter || !rightParameter {
			if leftParameter != rightParameter || leftSegment != rightSegment {
				return false
			}
			continue
		}
		if leftSegment != rightSegment {
			return true
		}
	}
	return false
}

func validRouteParameterName(name string) bool {
	if name == "" {
		return false
	}
	for index, character := range name {
		if index == 0 {
			if character != '_' &&
				(character < 'A' || character > 'Z') &&
				(character < 'a' || character > 'z') {
				return false
			}
			continue
		}
		if character != '_' &&
			(character < 'A' || character > 'Z') &&
			(character < 'a' || character > 'z') &&
			(character < '0' || character > '9') {
			return false
		}
	}
	return true
}

func foundationHandler(implementation types.Type) bool {
	method := types.NewMethodSet(types.NewPointer(implementation)).Lookup(nil, "Handle")
	if method == nil {
		return false
	}
	signature, ok := method.Obj().Type().(*types.Signature)
	if !ok || signature.Params().Len() != 1 || signature.Results().Len() != 2 {
		return false
	}
	contextType, ok := signature.Params().At(0).Type().(*types.Named)
	if !ok || contextType.Obj().Pkg() == nil ||
		contextType.Obj().Pkg().Path() != "context" ||
		contextType.Obj().Name() != "Context" {
		return false
	}
	return types.Identical(signature.Results().At(0).Type(), types.Universe.Lookup("any").Type()) &&
		types.Identical(signature.Results().At(1).Type(), types.Universe.Lookup("error").Type())
}

func (m *packageModel) render() ([]byte, error) {
	if len(m.routes) > 0 {
		m.imports.add(webPath, "foundationweb")
	}
	if len(m.actions) > 0 {
		m.imports.add(actionsPath, "foundationactions")
	}
	if len(m.routes) > 0 || len(m.actions) > 0 {
		m.imports.add(appPath, "foundationapp")
	}

	var source bytes.Buffer
	source.WriteString(generatedMark + "\n")
	fmt.Fprintf(&source, "package %s\n", m.name)
	m.imports.write(&source)

	for _, item := range m.contracts {
		fmt.Fprintf(&source, "\nvar _ %s = (*%s)(nil)\n", item.target, item.implementation)
	}
	if len(m.routes) > 0 {
		source.WriteString("\nfunc FoundationHTTPHandlers() []foundationweb.HandlerDefinition {\n")
		source.WriteString("\treturn []foundationweb.HandlerDefinition{\n")
		for _, item := range m.routes {
			fmt.Fprintf(&source, "\t\t{Method: %q, Path: %q, New: func() foundationweb.Handler { return &%s{} }},\n",
				item.method, item.path, item.implementation)
		}
		source.WriteString("\t}\n}\n")
	}
	if len(m.actions) > 0 {
		source.WriteString("\nfunc FoundationActions() []foundationactions.Definition {\n")
		source.WriteString("\treturn []foundationactions.Definition{\n")
		for _, item := range m.actions {
			fmt.Fprintf(&source, "\t\t{Name: %q, Key: %q, New: func() foundationactions.Handler { return &%s{} }},\n",
				item.name, item.key, item.implementation)
		}
		source.WriteString("\t}\n}\n")
	}
	if len(m.routes) > 0 || len(m.actions) > 0 {
		source.WriteString("\nfunc RegisterFoundation(application *foundationapp.App) {\n")
		if len(m.routes) > 0 {
			source.WriteString("\tapplication.RegisterHTTPDefinitions(FoundationHTTPHandlers()...)\n")
		}
		if len(m.actions) > 0 {
			source.WriteString("\tapplication.RegisterActionDefinitions(FoundationActions()...)\n")
		}
		source.WriteString("}\n")
	}

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("foundation generate: format %s: %w\n%s", m.path, err, source.String())
	}
	return formatted, nil
}

func genericSelector(expr ast.Expr, pkg *packages.Package, path, name string) ([]ast.Expr, bool) {
	var base ast.Expr
	var args []ast.Expr
	switch value := expr.(type) {
	case *ast.IndexExpr:
		base = value.X
		args = []ast.Expr{value.Index}
	case *ast.IndexListExpr:
		base = value.X
		args = value.Indices
	default:
		return nil, false
	}
	selector, ok := base.(*ast.SelectorExpr)
	if !ok {
		return nil, false
	}
	object, ok := pkg.TypesInfo.Uses[selector.Sel].(*types.TypeName)
	return args, ok && object.Pkg() != nil && object.Pkg().Path() == path && object.Name() == name
}

func writeFile(path string, content []byte) error {
	if current, err := os.ReadFile(path); err == nil {
		if !bytes.HasPrefix(current, []byte(generatedMark)) {
			return fmt.Errorf("foundation generate: refusing to overwrite non-generated file %s", path)
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	temp, err := os.CreateTemp(filepath.Dir(path), ".foundation-*.tmp")
	if err != nil {
		return err
	}
	tempName := temp.Name()
	defer os.Remove(tempName)

	if _, err := temp.Write(content); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Chmod(0o644); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	return os.Rename(tempName, path)
}

func removeGeneratedFile(path string) error {
	content, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !bytes.HasPrefix(content, []byte(generatedMark)) {
		return fmt.Errorf("foundation generate: refusing to remove non-generated file %s", path)
	}
	return os.Remove(path)
}

func canonicalModuleRoot(dir string) (string, error) {
	current, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(current, "go.mod")); err == nil {
			resolved, err := filepath.EvalSymlinks(current)
			if err != nil {
				return "", err
			}
			return resolved, nil
		} else if !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", fmt.Errorf("foundation generate: no go.mod found from %s", dir)
		}
		current = parent
	}
}

func canonicalPackageDirectory(file, moduleRoot string) (string, error) {
	directory, err := filepath.EvalSymlinks(filepath.Dir(file))
	if err != nil {
		return "", err
	}
	if err := ensureWithinModule(directory, moduleRoot); err != nil {
		return "", err
	}
	return directory, nil
}

func ensureWithinModule(path, moduleRoot string) error {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	relative, err := filepath.Rel(moduleRoot, absolute)
	if err != nil {
		return err
	}
	if relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return fmt.Errorf("foundation generate: path outside module root: %s", path)
	}
	return nil
}

type importSpec struct {
	path  string
	alias string
}

type imports struct {
	current string
	byPath  map[string]string
	used    map[string]string
}

func newImports(current string) *imports {
	return &imports{
		current: current,
		byPath:  make(map[string]string),
		used:    make(map[string]string),
	}
}

func (i *imports) qualifier(pkg *types.Package) string {
	if pkg == nil || pkg.Path() == i.current {
		return ""
	}
	return i.add(pkg.Path(), pkg.Name())
}

func (i *imports) add(path, preferred string) string {
	if alias, ok := i.byPath[path]; ok {
		return alias
	}
	alias := preferred
	for suffix := 2; ; suffix++ {
		if usedPath, exists := i.used[alias]; !exists || usedPath == path {
			break
		}
		alias = preferred + strconv.Itoa(suffix)
	}
	i.byPath[path] = alias
	i.used[alias] = path
	return alias
}

func (i *imports) write(target *bytes.Buffer) {
	if len(i.byPath) == 0 {
		return
	}
	specs := make([]importSpec, 0, len(i.byPath))
	for path, alias := range i.byPath {
		specs = append(specs, importSpec{path: path, alias: alias})
	}
	sort.Slice(specs, func(a, b int) bool {
		return specs[a].path < specs[b].path
	})

	target.WriteString("\nimport (\n")
	for _, spec := range specs {
		fmt.Fprintf(target, "\t%s %q\n", spec.alias, spec.path)
	}
	target.WriteString(")\n")
}
