// Code generated by foundation generate. DO NOT EDIT.

package quickstart

import (
	foundationapp "github.com/mirkobrombin/go-foundation/v2/app"
	foundationactions "github.com/mirkobrombin/go-foundation/v2/app/actions"
	foundationweb "github.com/mirkobrombin/go-foundation/v2/app/web"
)

var _ UserStore = (*MemoryUserStore)(nil)

func FoundationHTTPHandlers() []foundationweb.HandlerDefinition {
	return []foundationweb.HandlerDefinition{
		{Method: "GET", Path: "/users/{id:int}", New: func() foundationweb.Handler { return &GetUser{} }},
	}
}

func FoundationActions() []foundationactions.Definition {
	return []foundationactions.Definition{
		{Name: "users.create", Key: "ctrl+n", New: func() foundationactions.Handler { return &CreateUser{} }},
	}
}

func RegisterFoundation(application *foundationapp.App) {
	application.RegisterHTTPDefinitions(FoundationHTTPHandlers()...)
	application.RegisterActionDefinitions(FoundationActions()...)
}
